[project]
name = "imp_skizz_podcast"
version = "0.1.0"
description = ""
authors = [{ name = "Jack", email = "jack@jackwhitworth.com" }]
requires-python = ">=3.13,<4"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "django>=5.2.3,<6",
    "django-cors-headers>=4.7.0,<5",
    "gunicorn>=23.0.0,<24",
    "google-api-python-client>=2.174.0,<3",
    "requests>=2.32.4,<3",
    "whitenoise>=6.9.0,<7",
    "django-import-export>=4.4.1,<5",
    "psycopg2-binary>=2.9.12,<3",
]

[dependency-groups]
dev = [
    "black>=24.10.0,<25",
    "djhtml>=3.0.8,<4",
    "isort>=5.13.2,<6",
    "factory-boy>=3.3.3,<4",
]

[tool.uv]
package = false
default-groups = "all"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
