[project]
name = "django-boilerplate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "jmwhitworth", email = "jackmartinwhit@gmail.com" }]
requires-python = ">=3.13"
dependencies = [
    "django>=6.0.8",
    "django-cors-headers>=4.9.0",
    "django-debug-toolbar>=7.0.0",
    "django-tasks-db>=0.12.0",
    "django-vite>=3.1.0",
    "gunicorn>=26.0.0",
    "hiredis>=3.4.0",
    "psycopg2-binary>=2.9.12",
    "redis>=8.1.0",
    "whitenoise>=6.12.0",
]

[dependency-groups]
dev = [
    "black>=26.5.1",
    "coverage>=7.15.3",
    "django-debug-toolbar>=7.0.0",
    "django-zeal>=2.2.2",
    "djhtml>=3.0.11",
    "factory-boy>=3.3.3",
    "isort>=8.0.1",
]
