# Generated by Django 4.2.16 on 2024-10-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='youtube_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
