# Generated by Django 4.2.16 on 2024-10-21 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_podcast_youtube_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='description',
        ),
    ]
