# Generated by Django 4.2.16 on 2024-10-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_remove_podcast_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='episode_number',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
