# Generated by Django 4.2.16 on 2024-10-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0004_podcast_episode_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='spotify_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
