# Generated by Django 4.2.16 on 2024-10-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0005_podcast_spotify_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='apple_music_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
