# Generated by Django 4.2.16 on 2024-10-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0006_podcast_apple_music_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='spotify_id',
        ),
        migrations.AddField(
            model_name='podcast',
            name='spotify_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
