# Generated by Django 4.2.16 on 2024-10-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0007_remove_podcast_spotify_id_podcast_spotify_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='apple_music_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='spotify_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='podcasts', to='podcasts.tag'),
        ),
    ]
