# Generated by Django 4.2.16 on 2024-11-04 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0009_alter_podcast_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
