# Generated by Django 4.2.16 on 2024-11-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0010_remove_podcast_tags_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='podcast',
            name='preview_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
