# Generated by Django 5.2.15 on 2026-08-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0011_podcast_duration_podcast_preview_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="episode_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
