# Generated by Django 5.2.15 on 2026-08-10 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0012_podcast_archived_alter_podcast_episode_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="podcast",
            options={
                "ordering": ["-release_date"],
                "verbose_name": "Podcast",
                "verbose_name_plural": "Podcasts",
            },
        ),
    ]
