# Generated by Django 6.0.8 on 2026-08-25 14:31

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="YoutubeVideo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "video_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("video", "Video"), ("short", "Short")],
                        default="video",
                        max_length=10,
                    ),
                ),
                ("published_at", models.DateTimeField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
