# Generated by Django 6.0.8 on 2026-08-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0002_youtubevideo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="youtubevideo",
            options={
                "verbose_name": "YouTube Video",
                "verbose_name_plural": "YouTube Videos",
            },
        ),
        migrations.AddField(
            model_name="youtubevideo",
            name="api_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
