# Generated by Django 6.0.8 on 2026-08-25 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0003_alter_youtubevideo_options_youtubevideo_api_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="youtubevideo",
            options={
                "ordering": ["-published_at"],
                "verbose_name": "YouTube Video",
                "verbose_name_plural": "YouTube Videos",
            },
        ),
        migrations.RemoveField(
            model_name="youtubevideo",
            name="kind",
        ),
    ]
