# Generated by Django 6.0.8 on 2026-08-25 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0004_alter_youtubevideo_options_remove_youtubevideo_kind"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="podcast",
            options={
                "ordering": ["-release_date", "-season", "-episode"],
                "verbose_name": "Podcast",
                "verbose_name_plural": "Podcasts",
            },
        ),
        migrations.AddField(
            model_name="podcast",
            name="youtube_video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="podcasts",
                to="podcast.youtubevideo",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="podcast",
            unique_together={("season", "episode")},
        ),
    ]
