# Generated by Django 6.0.8 on 2026-08-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0005_alter_podcast_options_podcast_youtube_video_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="youtubevideo",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PUBLISHED", "Published"),
                    ("ARCHIVED", "Archived"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
