# Generated by Django 6.0.8 on 2026-08-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0006_youtubevideo_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcast",
            name="status",
            field=models.CharField(
                choices=[("PUBLISHED", "Published"), ("ARCHIVED", "Archived")],
                default="PUBLISHED",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="youtubevideo",
            name="status",
            field=models.CharField(
                choices=[("PUBLISHED", "Published"), ("ARCHIVED", "Archived")],
                default="PUBLISHED",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
