# Generated by Django 6.0.8 on 2026-08-26 13:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0007_alter_podcast_status_alter_youtubevideo_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpotifyEpisode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("PUBLISHED", "Published"), ("ARCHIVED", "Archived")],
                        default="PUBLISHED",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "episode_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("release_date", models.DateField()),
                ("duration_ms", models.PositiveIntegerField()),
                ("href", models.URLField(blank=True, max_length=255, null=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("api_data", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Spotify Upload",
                "verbose_name_plural": "Spotify Uploads",
                "ordering": ["-release_date", "-id"],
            },
        ),
        migrations.AlterModelOptions(
            name="youtubevideo",
            options={
                "ordering": ["-published_at", "-id"],
                "verbose_name": "YouTube Video",
                "verbose_name_plural": "YouTube Videos",
            },
        ),
        migrations.AddField(
            model_name="podcast",
            name="spotify_episode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="podcasts",
                to="podcast.spotifyepisode",
            ),
        ),
    ]
