# Generated by Django 6.0.8 on 2026-08-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0008_spotifyepisode_alter_youtubevideo_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="spotifyepisode",
            name="preview_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
